name: sword2
channels:
  - defaults
  - conda-forge
  - salilab
dependencies:
  - python==3.10
  - perl==5.32
  - dssp
  - pip
  - pip:
    - requests
    - plotly
    - numpy
    - pandas
    - matplotlib
    - prody
    - kaleido
    - urllib3
