[package]
name = "sword2"
version = "2.0.0"
edition = "2021"
description = "SWORD2: SWift and Optimized Recognition of protein Domains"

[[bin]]
name = "sword2"
path = "src/main.rs"

[dependencies]
sword2-lib = { path = "../sword2-lib" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
num_cpus = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
